### ISSUE TITLE
Serializable

### ISSUE THREAD

**Issue by eakarsu** [inoio/solrs#78]
Martin
Can you make library Serializable?
I am trying to use it in spark application but cannot use it due to unserializable?
Thanks

**Comment by magro** [comment]
Hi @eakarsu, can you please be more specific? What would have to be changed? A PR would be highly welcome of course :-)

**Comment by eakarsu** [comment]
Margo,
If you can make RoundRobinLB and FastestServerLB serializable, then I can use them in Spark.
Currently, If I use them in spark application, I am getting unserializable  exception. The reason is that every time I do . Here I tried to use either RoundRobinLB and FastestServerLB but getting the following exception in spark application.I am not sure whether or not we can make this. Just make a small spark app and initialize RoundRobinLB and FastestServerLB  and try to get solr url with lb.solrServer(r).get.baseUrl in map-reduce loop. You will get this exception. I tried to use  FastestServerLB but this method is called by spark multiple times and gives exception "Object is already registered". We should make this FastestServerLB so that it can b e used in multi-threaded applications. If you need more info, then please let me know

def initJmx(): Unit = {
    ManagementFactory.getPlatformMBeanServer.registerMBean(this, ObjName)
  }


 def getDynamicLB(zkHost:String) = {
    val t0 = System.nanoTime()
    val solrServers = new CloudSolrServers(zkHost,defaultCollection = Some(solrColl)) with  Serializable
    val lb = new RoundRobinLB(solrServers)  with  Serializable
    val client = AsyncSolrClient.Builder(lb).withRetryPolicy(RetryPolicy.TryAvailableServers).build
    val t1 = System.nanoTime()
    println (s"getDynamicLB took time ${t1-t0} ns")
    lb
  }

Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:403)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:393)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
	at org.apache.spark.rdd.RDD.$anonfun$flatMap$1(RDD.scala:380)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.flatMap(RDD.scala:379)
	at com.lowes.SolrIndexWithSpark.getAllProductIds(SolrIndexWithSpark.scala:416)
	at com.lowes.SolrIndexWithSpark.processIdBlocks(SolrIndexWithSpark.scala:403)
	at com.lowes.SolrIndexWithSpark$.main(SolrIndexWithSpark.scala:849)
	at com.lowes.SolrIndexWithSpark.main(SolrIndexWithSpark.scala)
Caused by: java.io.NotSerializableException: io.ino.solrs.RoundRobinLB
Serialization stack:
	- object not serializable (class: io.ino.solrs.RoundRobinLB, value: io.ino.solrs.RoundRobinLB@6940f685)
	- field (class: com.lowes.SolrIndexWithSpark, name: lb, type: class io.ino.solrs.RoundRobinLB)
	- object (class com.lowes.SolrIndexWithSpark, com.lowes.SolrIndexWithSpark@243f003c)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 4)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class com.lowes.SolrIndexWithSpark,

**Comment by magro** [comment]
Ok. Can you submit a PR? This would probably speed up things... ;-)

**Comment by eakarsu** [comment]
Ok 
Let me do it

**Comment by eakarsu** [comment]
But  Martin, I don't have a solution. how can I create PR?

**Comment by magro** [comment]
@eakarsu I've pushed s.th. to https://github.com/inoio/solrs/tree/round-robin-lb_serializable_issue78 - what do you think of this?

**Comment by eakarsu** [comment]
Is it so fast Martin? I will test and let you know.
One more thing. After I call inoio and get active solrs from zk, then I shutdown  lb and client. but the app is still hanging. Is there a call I should make for app to exit gracefully?

def getSolrHosts(zkHost:String,solrColl:String) = {
      val t0 = System.nanoTime()
      val solrServers = new CloudSolrServers(zkHost,defaultCollection = Some(solrColl))
      val lb = new RoundRobinLB(solrServers)
      val client = AsyncSolrClient.Builder(lb).withRetryPolicy(RetryPolicy.TryAvailableServers).build
      val t1 = System.nanoTime()
      println (s"getDynamicLB took time ${t1-t0} ns")
      val iphosts = lb.solrServers.all.filter(x=>x.baseUrl.contains(s"/${solrColl}_shard")).
          map(x=>x.baseUrl.replace("http://","").
          replaceAll(":.*$","")).toList
      lb.shutdown()
      client.shutdown()
      iphosts
    }

**Comment by eakarsu** [comment]
When I cancel the app (because it is hanging), getting this error:

[warn] Canceling execution...
[error] Total time: 141 s (02:21), completed Feb 25, 2020 2:34:40 PM
[warn] Run canceled.
Exception in thread "sbt-bg-threads-1" java.util.concurrent.RejectedExecutionException
	at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2328)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2419)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.$anonfun$cleanup$1(DefaultBackgroundJobService.scala:390)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.$anonfun$cleanup$1$adapted(DefaultBackgroundJobService.scala:389)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.cleanup(DefaultBackgroundJobService.scala:389)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:359)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by magro** [comment]
@eakarsu Can you please submit a separate issue regarding shutdown ending with hanging app?

**Comment by magro** [comment]
@eakarsu is this still relevant? If not please close this issue.

**Comment by magro** [comment]
Closed due to missing feedback.
